### ISSUE TITLE
History seems to be broken

### ISSUE THREAD

**Issue by 0xTriboulet** [pepperoni21/ollama-rs#90]
Code:
```rust
use ollama_rs::{
    generation::chat::{request::ChatMessageRequest, ChatMessage},
    Ollama,
};
use tokio::io::{stdout, AsyncWriteExt};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut ollama = Ollama::new_default_with_history(30u16);

    let mut stdout = stdout();

    loop {
        stdout.write_all(b"\n> ").await?;
        stdout.flush().await?;

        let mut input = String::new();
        std::io::stdin().read_line(&mut input)?;

        let input = input.trim_end();
        if input.eq_ignore_ascii_case("exit") {
            break;
        }

        let user_message = ChatMessage::user(input.to_string());

        let result = ollama
            .send_chat_messages_with_history(
                ChatMessageRequest::new("llama3.2:latest".to_string(), vec![user_message]),
                "default",
            )
            .await?;

        let assistant_message = result.message.unwrap().content;
        stdout.write_all(assistant_message.as_bytes()).await?;
        stdout.flush().await?;
    }

    // Display whole history of messages
    println!("{:#?}",&ollama.get_messages_history("default"));

    Ok(())
}
```

Cargo.toml
```
[package]
name = "DELETE_ME_OLLAMA_HISTORY_TEST"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama-rs = { version = "0.2.1", features = ["stream", "function-calling", "chat-history", "default"] }
tokio = { version = "1.41.1", features = ["io-std", "rt", "rt-multi-thread", "macros"] }

```

Cargo version:
```
cargo --version
cargo 1.82.0 (8f40fc59f 2024-08-21)
```

Output
```
Initializing MessagesHistory with limit: 30

> test
messages_number_limit: 0
thread 'main' panicked at C:\Users\0xtriboulet\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ollama-rs-0.2.1\src\history.rs:46:22:
removal index (is 0) should be < len (is 0)
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: alloc::vec::impl$1::remove::assert_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/alloc\src\vec\mod.rs:1633
   3: ollama_rs::history::MessagesHistory::add_message
   4: ollama_rs::generation::chat::<impl ollama_rs::Ollama>::store_chat_message_by_id
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: tokio::runtime::runtime::Runtime::block_on
   8: <tokio::sync::mpsc::chan::Chan<T,S> as core::ops::drop::Drop>::drop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The `Initializing MessagesHistory with limit: 30` and `messages_number_limit: 0` are debug print statements I added to `history.rs`. It seems that it is initialized with the correct limit but when code execution gets to the `add_message` part of the code, the limit has been reset to 0?

Adding the `chat-history` feature to `Cargo.toml` clears the panic, but history still doesn't work

```
> my name is steve
Hello Steve! It's nice to meet you. Is there something I can help you with, or would you like to chat?
> what is my name
I don't have any information about your name. I'm a conversational AI, and our conversation just started. I don't retain any information from previous conversations or interactions. If you'd like to share your name with me, I'd be happy to chat with you!
```

**Comment by boydjohnson** [comment]
@0xTriboulet I agree. There is something wonky. 

These lines seem suspect (a default MessagesHistory is being set to self.message_history).

https://github.com/pepperoni21/ollama-rs/blob/b20a99857da206288210cf53c0e1de44b59894db/src/generation/chat/mod.rs#L210-L215

Making this change gets your example to work.

```
git diff
diff --git a/src/generation/chat/mod.rs b/src/generation/chat/mod.rs
index 6971587..abb3ceb 100644
--- a/src/generation/chat/mod.rs
+++ b/src/generation/chat/mod.rs
@@ -210,8 +210,7 @@ impl Ollama {
         let mut binding = {
             let new_history =
                 std::sync::Arc::new(std::sync::RwLock::new(MessagesHistory::default()));
-            self.messages_history = Some(new_history);
-            self.messages_history.clone().unwrap()
+            new_history
         };
         let chat_history = match self.messages_history.as_mut() {
             Some(history) => history,
```

```
./target/release/DELETE_ME_OLLAMA_HISTORY_TEST

> My name is Steve.
Nice to meet you, Steve! Is there something I can help you with or would you like to chat?
> What is my name?
You told me earlier that your name is Steve.
> exit
Some(
    [
        ChatMessage {
            role: User,
            content: "My name is Steve.",
            images: None,
        },
        ChatMessage {
            role: Assistant,
            content: "Nice to meet you, Steve! Is there something I can help you with or would you like to chat?",
            images: None,
        },
        ChatMessage {
            role: User,
            content: "What is my name?",
            images: None,
        },
        ChatMessage {
            role: Assistant,
            content: "You told me earlier that your name is Steve.",
            images: None,
        },
    ],
)
```

**Comment by 0xTriboulet** [comment]
Thanks for the pointer. So I was able to get the same results with a different change, dunno if there's a preferred change for the architecture of the library

```rust
    fn get_chat_messages_by_id(&mut self, history_id: impl ToString) -> Vec<ChatMessage> {
        let mut binding = {
            let new_history =
                std::sync::Arc::new(std::sync::RwLock::new(MessagesHistory::default()));
            new_history
        };
```

```
> my name is steve
Hello Steve! It's nice to meet you. Is there something I can help you with or would you like to chat?
> what is my name
Your name, as we've established earlier, is Steve. How's your day going so far?
> what is my name
You told me your name earlier, and it's still Steve! Is there something on your mind that you'd like to talk about or ask about? I'm here to help!
> exit
Some(
    [
        ChatMessage {
            role: User,
            content: "my name is steve",
            images: None,
        },
        ChatMessage {
            role: Assistant,
            content: "Hello Steve! It's nice to meet you. Is there something I can help you with or would you like to chat?",
            images: None,
        },
        ChatMessage {
            role: User,
            content: "what is my name",
            images: None,
        },
        ChatMessage {
            role: Assistant,
            content: "Your name, as we've established earlier, is Steve. How's your day going so far?",
            images: None,
        },
        ChatMessage {
            role: User,
            content: "what is my name",
            images: None,
        },
        ChatMessage {
            role: Assistant,
            content: "You told me your name earlier, and it's still Steve! Is there something on your mind that you'd like to talk about or ask about? I'm here to help!",
            images: None,
        },
    ],
)

Process finished with exit code 0
```
